# Generated by Django 2.2.6 on 2019-10-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name Of the product', max_length=40)),
                ('brand', models.CharField(help_text='Name Of the Fertilizer Company', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('joinDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateField()),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fertilizer')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Greenhouse')),
                ('plantRecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PlantRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name Of the Greenhouse', max_length=40)),
                ('dateCertified', models.DateField(verbose_name='datetime Certified')),
                ('type', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=0, max_digits=3)),
                ('requiredScore', models.DecimalField(decimal_places=0, max_digits=3)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Greenhouse')),
            ],
        ),
    ]
