# Generated by Django 2.2.6 on 2019-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial2'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantrecipe',
            name='name',
            field=models.CharField(default='', help_text='Name Of the plant', max_length=40),
            preserve_default=False,
        ),
    ]
