# Generated by Django 2.2.6 on 2019-10-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of Soil Type', max_length=40)),
                ('pH', models.DecimalField(decimal_places=3, max_digits=5)),
                ('nitrogen', models.DecimalField(decimal_places=0, max_digits=3)),
                ('phosphorus', models.DecimalField(decimal_places=0, max_digits=3)),
                ('potassium', models.DecimalField(decimal_places=0, max_digits=3)),
                ('calcium', models.DecimalField(decimal_places=0, max_digits=3)),
                ('copper', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sulphur', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='soil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Soil'),
        ),
    ]
