# Generated by Django 2.2.6 on 2019-10-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191019_1853'),
        ('app', '0002_plantrecipe_name'),
    ]

    operations = [
    ]
