<<<<<<< HEAD
# Generated by Django 2.2.6 on 2019-10-19 21:15
=======
# Generated by Django 2.2.6 on 2019-10-20 00:02
>>>>>>> f90bb22a24c5dd8f15ae6389d16a4dcd4d16aa48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('app', '0003_merge_20191019_2113'),
=======
        ('app', '0003_merge_20191019_1952'),
>>>>>>> f90bb22a24c5dd8f15ae6389d16a4dcd4d16aa48
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
