# Generated by Django 2.2.6 on 2019-10-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_certification_description'),
        ('app', '0003_merge_20191019_1952'),
    ]

    operations = [
    ]
